/**
 * شعارات ماركات السيارات - توليد تلقائي
 * يتم استخدام require للسماح لـ Metro Bundler بتضمين الصور محلياً.
 */

export const BRAND_LOGOS: Record<string, any> = {
  'acura': require('../../assets/images/brands/acura.png'),
  'alfa-romeo': require('../../assets/images/brands/alfa-romeo.png'),
  'alpine': require('../../assets/images/brands/alpine.png'),
  'aston-martin': require('../../assets/images/brands/aston-martin.png'),
  'audi': require('../../assets/images/brands/audi.png'),
  'baic': require('../../assets/images/brands/baic.png'),
  'bentley': require('../../assets/images/brands/bentley.png'),
  'bestune': require('../../assets/images/brands/bestune.png'),
  'bmw': require('../../assets/images/brands/bmw.png'),
  'bugatti': require('../../assets/images/brands/bugatti.png'),
  'byd': require('../../assets/images/brands/byd.png'),
  'cadillac': require('../../assets/images/brands/cadillac.png'),
  'changan': require('../../assets/images/brands/changan.png'),
  'chery': require('../../assets/images/brands/chery.png'),
  'chevrolet': require('../../assets/images/brands/chevrolet.png'),
  'citroen': require('../../assets/images/brands/citroen.png'),
  'daihatsu': require('../../assets/images/brands/daihatsu.png'),
  'dodge': require('../../assets/images/brands/dodge.png'),
  'exeed': require('../../assets/images/brands/exeed.png'),
  'ferrari': require('../../assets/images/brands/ferrari.png'),
  'fiat': require('../../assets/images/brands/fiat.png'),
  'ford': require('../../assets/images/brands/ford.png'),
  'fuso': require('../../assets/images/brands/fuso.png'),
  'gac': require('../../assets/images/brands/gac.png'),
  'geely': require('../../assets/images/brands/geely.png'),
  'genesis': require('../../assets/images/brands/genesis.png'),
  'gmc': require('../../assets/images/brands/gmc.png'),
  'great-wall': require('../../assets/images/brands/great-wall.png'),
  'haval': require('../../assets/images/brands/haval.png'),
  'hino': require('../../assets/images/brands/hino.png'),
  'honda': require('../../assets/images/brands/honda.png'),
  'hongqi': require('../../assets/images/brands/hongqi.png'),
  'hummer': require('../../assets/images/brands/hummer.png'),
  'hyundai': require('../../assets/images/brands/hyundai.png'),
  'infiniti': require('../../assets/images/brands/infiniti.png'),
  'isuzu': require('../../assets/images/brands/isuzu.png'),
  'iveco': require('../../assets/images/brands/iveco.png'),
  'jaguar': require('../../assets/images/brands/jaguar.png'),
  'jeep': require('../../assets/images/brands/jeep.png'),
  'kia': require('../../assets/images/brands/kia.png'),
  'koenigsegg': require('../../assets/images/brands/koenigsegg.png'),
  'lamborghini': require('../../assets/images/brands/lamborghini.png'),
  'lancia': require('../../assets/images/brands/lancia.png'),
  'land-rover': require('../../assets/images/brands/land-rover.png'),
  'lexus': require('../../assets/images/brands/lexus.png'),
  'lincoln': require('../../assets/images/brands/lincoln.png'),
  'lotus': require('../../assets/images/brands/lotus.png'),
  'lucid': require('../../assets/images/brands/lucid.png'),
  'mahindra': require('../../assets/images/brands/mahindra.png'),
  'man': require('../../assets/images/brands/man.png'),
  'maserati': require('../../assets/images/brands/maserati.png'),
  'maxus': require('../../assets/images/brands/maxus.png'),
  'maybach': require('../../assets/images/brands/maybach.png'),
  'mazda': require('../../assets/images/brands/mazda.png'),
  'mclaren': require('../../assets/images/brands/mclaren.png'),
  'mercedes-benz': require('../../assets/images/brands/mercedes-benz.png'),
  'mg': require('../../assets/images/brands/mg.png'),
  'mini': require('../../assets/images/brands/mini.png'),
  'mitsubishi': require('../../assets/images/brands/mitsubishi.png'),
  'nissan': require('../../assets/images/brands/nissan.png'),
  'opel': require('../../assets/images/brands/opel.png'),
  'pagani': require('../../assets/images/brands/pagani.png'),
  'peugeot': require('../../assets/images/brands/peugeot.png'),
  'polestar': require('../../assets/images/brands/polestar.png'),
  'pontiac': require('../../assets/images/brands/pontiac.png'),
  'porsche': require('../../assets/images/brands/porsche.png'),
  'proton': require('../../assets/images/brands/proton.png'),
  'ram': require('../../assets/images/brands/ram.png'),
  'renault': require('../../assets/images/brands/renault.png'),
  'rivian': require('../../assets/images/brands/rivian.png'),
  'rolls-royce': require('../../assets/images/brands/rolls-royce.png'),
  'saab': require('../../assets/images/brands/saab.png'),
  'scania': require('../../assets/images/brands/scania.png'),
  'seat': require('../../assets/images/brands/seat.png'),
  'smart': require('../../assets/images/brands/smart.png'),
  'ssangyong': require('../../assets/images/brands/ssangyong.png'),
  'subaru': require('../../assets/images/brands/subaru.png'),
  'suzuki': require('../../assets/images/brands/suzuki.png'),
  'tata': require('../../assets/images/brands/tata.png'),
  'tesla': require('../../assets/images/brands/tesla.png'),
  'toyota': require('../../assets/images/brands/toyota.png'),
  'vinfast': require('../../assets/images/brands/vinfast.png'),
  'volkswagen': require('../../assets/images/brands/volkswagen.png'),
  'volvo': require('../../assets/images/brands/volvo.png'),
};

export function getBrandLogo(brandKey: string): any {
  if (!brandKey) return null;
  const key = brandKey.toLowerCase().trim();
  return BRAND_LOGOS[key] || null;
}
