name: Expo EAS Update

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    name: Publish EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Create .env file for build
        run: |
          echo "EXPO_PUBLIC_API_URL=https://caroneapi-production-255b.up.railway.app/api/v1" >> .env
          echo "EXPO_PUBLIC_SOCKET_URL=https://caroneapi-production-255b.up.railway.app" >> .env
          echo "EXPO_PUBLIC_CLOUDINARY_CLOUD=dityoyp85" >> .env

      - name: Publish Update
        run: eas update --branch preview --message "${{ github.event.head_commit.message }}" --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
